Repository Yammy-expedition/Dotted-frontend, pull requests merged in 2025-03, with the labels that each got.

#78 fix: style
  index.html
  src/components/SignUpPage/AgreeBox.tsx
  src/components/SignUpPage/AgreeItem.tsx
  src/components/SignUpPage/CreateEmailButton.tsx
  src/components/SignUpPage/GooleLoginButton.tsx
  src/components/SignUpPage/MainText.tsx
  src/components/SignUpPage/Recomended.tsx
  src/components/SignUpPage/SignUpForm.tsx
  src/components/SignUpPage/SignUpWithOtherEmail.tsx
  src/components/SignUpPage/SignUpWithSogangEmail.tsx
  src/components/SignUpPage/SogangSignUpButton.tsx
  src/components/SignUpPage/StudentVerification.tsx
  src/components/common/Login,SignUp/BackButton.tsx
  src/components/common/Login,SignUp/Greeting.tsx
  src/components/common/Login,SignUp/PageLayout.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/SubHeader.tsx
  src/components/common/header/header-items/HeaderNav.tsx
  src/components/tips/sogang-map/KakaoMap.tsx
  src/components/tips/sogang-map/MapModal.tsx
  src/pages/Google.tsx
  src/pages/SignUpPage.tsx
  src/pages/about/OnboardingPage.tsx
  src/pages/tips/culture/CultureDetailPage.tsx
  src/pages/tips/culture/CulturePage.tsx
  src/style/Theme.ts
  tsconfig.tsbuildinfo
Labels: 🎨 Html&css, 🐞 BugFix, ✨ Feature

#79 Fix/qa byul
  src/components/CommunityPage/CommentSection.tsx
  src/components/CommunityPage/MoreButton.tsx
  src/components/LoginPage/ForgetPassPage/SendCodePart.tsx
  src/components/LoginPage/ForgetPassPage/VerifyCodePart.tsx
  src/components/LoginPage/LoginForm.tsx
  src/components/MainPage/Carousel.tsx
  src/components/MarketPage/MakrketList.tsx
  src/components/MarketPage/MarketPosting.tsx
  src/components/SignUpPage/EmailVerification.tsx
  src/components/SignUpPage/Nickname.tsx
  src/components/SignUpPage/StudentVerification.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/SubHeader.tsx
  src/components/common/header/header-items/HeaderNav.tsx
  src/components/common/header/header-items/ProfileButton.tsx
  src/components/mypage/my-comments/CommunityComments.tsx
  src/components/mypage/my-comments/MarketComments.tsx
  src/components/tips/culture/CultureList.tsx
  src/components/tips/restaurant/RestaurantList.tsx
  src/hooks/useSearchPosts.tsx
  src/pages/Google.tsx
  src/pages/MainPage.tsx
  src/pages/NotificatoinPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/admin/CultureCreatePage.tsx
  src/pages/community/DetailCommunityPage.tsx
  src/pages/community/WriteCommunityPage.tsx
  src/pages/market/DetailMarketPage.tsx
  src/pages/market/MarketPage.tsx
  src/pages/market/WriteMarketPage.tsx
  src/pages/mypage/VerificationPage.tsx
  src/utils/ImageExtractor.ts
  src/utils/Network.ts
  src/utils/auth.ts
Labels: 🎨 Html&css, 🐞 BugFix

#94 add: carousel banner
  package-lock.json
  package.json
  src/components/MainPage/Carousel.tsx
  src/components/MainPage/Tips.tsx
  src/components/common/Footer.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/header-items/HeaderNav.tsx
  src/components/common/header/header-items/LanguageButton.tsx
  src/components/common/header/header-items/ProfileButton.tsx
  src/locales/en/translation.json
  src/locales/i18n.tsx
  src/locales/ko/translation.json
  tsconfig.tsbuildinfo
Labels: ✨ Feature

#95 fix: fix/qa-byul
  src/components/common/header/Header.tsx
Labels: 🐞 BugFix

#96 fix: url
  src/components/MainPage/Carousel.tsx
Labels: 🐞 BugFix

#97 Feat/market page#35
  src/api/marketApi.ts
  src/components/CommunityPage/CommentContent.tsx
  src/components/CommunityPage/CommentInput.tsx
  src/components/CommunityPage/CommentSection.tsx
  src/components/CommunityPage/Posting.tsx
  src/components/MainPage/MarketMiniBoard.tsx
  src/components/MainPage/Tips.tsx
  src/components/Notification/NotificationItem.tsx
  src/components/SignUpPage/AccessRestrictedModal.tsx
  src/components/SignUpPage/SignUpModal.tsx
  src/components/SignUpPage/StudentVerification.tsx
  src/components/common/Footer.tsx
  src/components/common/ProtectedRoute.tsx
  src/hooks/Mainpage/useAuth.ts
  src/hooks/Mainpage/useHandleNavigation.ts
  src/hooks/Mainpage/useModal.ts
  src/hooks/useCommentHandlers.ts
  src/hooks/useNotification.ts
  src/hooks/useSignUp.ts
  src/hooks/useSignUpModal.ts
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
  src/style/GlobalStyles.ts
  src/utils/auth.ts
Labels: 🐞 BugFix, 🔨 Refactor, 💩chore

#98 fix: 배너 클릭 시 페이지 이동
  src/components/MainPage/Carousel.tsx
  src/hooks/useSignUp.ts
Labels: 🐞 BugFix

#100 fix: language
  src/components/MainPage/Tips.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/header-items/HeaderNav.tsx
  tsconfig.tsbuildinfo
Labels: 🐞 BugFix

#101 fix: beta period
  src/components/MainPage/Carousel.tsx
  src/components/about/notice/NoticeList.tsx
Labels: 🐞 BugFix

#103 chore: 베타 기간 방학 끝으로 수정
  src/components/MainPage/Carousel.tsx
  src/components/SignUpPage/AccessRestrictedModal.tsx
  src/components/about/notice/NoticeList.tsx
Labels: 💩chore
