Repository Yammy-expedition/Dotted-frontend, pull requests merged in 2025-02, with the labels that each got.

#34 feat: footer 구현 완료
  src/Router.tsx
  src/assets/svg/footer/Instagram.svg
  src/assets/svg/footer/Mail.svg
  src/components/common/Footer.tsx
  src/components/common/Logo.tsx
  src/components/common/header/HeaderLayout.tsx
Labels: 🎨 Html&css, ✨ Feature, 💩chore

#42 Feat/notification#40
  src/assets/svg/tips/faq/arrow.svg
  src/assets/svg/tips/hospital/distance.svg
  src/assets/svg/tips/hospital/left.svg
  src/assets/svg/tips/hospital/link.svg
  src/assets/svg/tips/hospital/right.svg
  src/components/CommunityPage/AComment.tsx
  src/components/CommunityPage/AReply.tsx
  src/components/CommunityPage/CommentSection.tsx
  src/components/CommunityPage/MoreButton.tsx
  src/components/CommunityPage/SearchBar.tsx
  src/components/LoginPage/ForgetPassPage/NewPasswordPart.tsx
  src/components/LoginPage/ForgetPassPage/VerifyCodePart.tsx
  src/components/LoginPage/LoginForm.tsx
  src/components/SignUpPage/EmailVerification.tsx
  src/components/SignUpPage/Nickname.tsx
  src/components/SignUpPage/StudentVerification.tsx
  src/components/common/header/Header.tsx
  src/components/tips/restaurant/RestaurantList.tsx
  src/components/tips/sogang-map/KakaoMap.tsx
  src/components/tips/sogang-map/SearchBox.tsx
  src/hooks/useFAQ.ts
  src/hooks/useHospital.ts
  src/hooks/usePasswordResetEmail.tsx
  src/hooks/useSearchPosts.tsx
  src/pages/Google.tsx
  src/pages/NotificatoinPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/community/DetailCommunityPage.tsx
  src/pages/community/WriteCommunityPage.tsx
  src/pages/market/DetailMarketPage.tsx
  src/pages/market/WriteMarketPage.tsx
  src/pages/tips/FAQPage.tsx
  src/pages/tips/HospitalPage.tsx
  src/utils/auth.ts
Labels: ✨ Feature, 📬 API

#43 feat: Enhance FAQPage with answer formatting and update HospitalPage …
  src/pages/tips/FAQPage.tsx
  src/pages/tips/HospitalPage.tsx
Labels: ✨ Feature, 📬 API

#48 서강 맵 구현
  index.html
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/svg/about/onboarding/club.svg
  src/assets/svg/about/onboarding/culture.svg
  src/assets/svg/about/onboarding/faq.svg
  src/assets/svg/about/onboarding/hospital.svg
  src/assets/svg/about/onboarding/map.svg
  src/assets/svg/about/onboarding/restaurant.svg
  src/components/about/onboarding/Community.tsx
  src/components/about/onboarding/LastSection.tsx
  src/components/about/onboarding/Market.tsx
  src/components/about/onboarding/TipsForSogang.tsx
  src/components/about/onboarding/WhatIsDotted.tsx
  src/components/about/onboarding/WhyCreated.tsx
  src/components/common/header/SubHeader.tsx
  src/components/tips/sogang-map/KakaoMap.tsx
  src/components/tips/sogang-map/MapModal.tsx
  src/components/tips/sogang-map/SearchBox.tsx
  src/constants/buildings.ts
  src/pages/about/NoticePage.tsx
  src/pages/about/OnboardingPage.tsx
  src/pages/tips/SogangMapPage.tsx
  tsconfig.tsbuildinfo
Labels: 🐞 BugFix, ✨ Feature

#54 서강맵 오류 수정
  src/components/tips/sogang-map/KakaoMap.tsx
  src/components/tips/sogang-map/MapModal.tsx
  src/components/tips/sogang-map/SearchBox.tsx
  src/constants/buildings.ts
  src/pages/tips/SogangMapPage.tsx
Labels: 🐞 BugFix

#60 fix: profile
  src/components/common/header/header-items/ProfileButton.tsx
  src/pages/MainPage.tsx
Labels: 🐞 BugFix

#61 fix: redirect url
  src/components/SignUpPage/GooleLoginButton.tsx
Labels: 🐞 BugFix

#62 fix: verify
  README.md
  src/pages/mypage/VerificationPage.tsx
  src/utils/auth.ts
Labels: 🐞 BugFix

#68 feat: feat
  src/Router.tsx
  src/components/CommunityPage/AComment.tsx
  src/components/CommunityPage/AReply.tsx
  src/components/CommunityPage/CommentSection.tsx
  src/components/CommunityPage/MoreButton.tsx
  src/components/CommunityPage/Posting.tsx
  src/components/CommunityPage/PostingList.tsx
  src/components/CommunityPage/SearchBar.tsx
  src/components/LoginPage/ForgetPassPage/HeadContent.tsx
  src/components/LoginPage/ForgetPassPage/VerifyCodePart.tsx
  src/components/LoginPage/LoginForm.tsx
  src/components/LoginPage/LoginWithOtherEmail.tsx
  src/components/LoginPage/SignUpPropmpt.tsx
  src/components/MainPage/Tips.tsx
  src/components/MarketPage/MakrketList.tsx
  src/components/MarketPage/MarketPosting.tsx
  src/components/SignUpPage/AccessRestrictedModal.tsx
  src/components/SignUpPage/AgreeItem.tsx
  src/components/SignUpPage/CreateEmailButton.tsx
  src/components/SignUpPage/EmailInputField.tsx
  src/components/SignUpPage/EmailVerification.tsx
  src/components/SignUpPage/GooleLoginButton.tsx
  src/components/SignUpPage/Group.tsx
  src/components/SignUpPage/Label.tsx
  src/components/SignUpPage/MainText.tsx
  src/components/SignUpPage/Recomended.tsx
  src/components/SignUpPage/SignUpWithOtherEmail.tsx
  src/components/SignUpPage/SogangSignUpButton.tsx
  src/components/SignUpPage/VerifyCodeInputField.tsx
  src/components/SignUpPage/VerifyCodeStatus.tsx
  src/components/WriteCommunityPage/TagBox.tsx
  src/components/about/notice/NoticeList.tsx
  src/components/common/Footer.tsx
  src/components/common/Login,SignUp/Divider.tsx
  src/components/common/Login,SignUp/Greeting.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderLayout.tsx
  src/components/common/header/header-items/HeaderNav.tsx
  src/components/common/header/header-items/ProfileButton.tsx
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/about/NoticeDetailPage.tsx
  src/pages/about/NoticePage.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/community/DetailCommunityPage.tsx
  src/pages/community/WriteCommunityPage.tsx
  src/pages/market/DetailMarketPage.tsx
  src/pages/market/MarketPage.tsx
  src/pages/market/WriteMarketPage.tsx
  src/pages/tips/FAQPage.tsx
  src/pages/tips/HospitalPage.tsx
  src/style/GlobalStyles.ts
  tsconfig.tsbuildinfo
Labels: 🐞 BugFix, ✨ Feature

#70 feat: sign verify
  src/components/SignUpPage/StudentVerification.tsx
Labels: 🐞 BugFix

#71 Fix/qa byul
  src/assets/svg/MainPage/Quote.svg
  src/assets/svg/mypage/check.svg
  src/components/MainPage/Carousel.tsx
  src/components/MainPage/Tips.tsx
  src/components/tips/sogang-map/MapModal.tsx
  src/pages/MainPage.tsx
  src/pages/mypage/VerificationPage.tsx
  src/pages/tips/SogangMapPage.tsx
Labels: 🐞 BugFix

#73 fix: login
  src/components/LoginPage/LoginForm.tsx
  src/components/LoginPage/LoginWithOtherEmail.tsx
  src/components/LoginPage/SignUpPropmpt.tsx
  src/components/common/Footer.tsx
  src/components/common/Login,SignUp/BackButton.tsx
  src/components/common/Login,SignUp/Divider.tsx
  src/components/common/Login,SignUp/Greeting.tsx
  src/components/common/Login,SignUp/PageLayout.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/SubHeader.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
  tsconfig.tsbuildinfo
Labels: 🐞 BugFix
